/**
 * Server module boundaries (A-04).
 *
 * Static guards for mistakes that type-checking cannot catch: a privileged
 * client reached from UI code, a client built once at module load and shared
 * between users, or a server module missing its `server-only` guard.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = join(import.meta.dirname, '..');

function sourceFiles(dir: string): string[] {
  const entries = readdirSync(join(repoRoot, dir), { withFileTypes: true });
  return entries.flatMap((entry) => {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory()) return sourceFiles(path);
    return entry.name.endsWith('.ts') || entry.name.endsWith('.tsx') ? [path] : [];
  });
}

// `database.types.ts` is generated by the Supabase CLI; it is data, not a module we author.
const GENERATED = new Set(['src/server/database.types.ts']);
const serverFiles = sourceFiles('src/server').filter((file) => !GENERATED.has(file));
const contractFiles = sourceFiles('src/contracts');
const uiFiles = [...sourceFiles('src/app'), ...sourceFiles('src/components'), ...sourceFiles('src/features')];

function read(path: string): string {
  return readFileSync(join(repoRoot, path), 'utf8');
}

describe('privileged client isolation', () => {
  it.each([...uiFiles, ...contractFiles])('%s does not import the admin client', (file) => {
    expect(read(file)).not.toMatch(/admin-client/);
  });

  it.each(contractFiles)('%s does not import server modules', (file) => {
    // Contracts ship to the browser; a server import here would break the
    // build at best and leak configuration at worst.
    expect(read(file)).not.toMatch(/from\s+'[^']*server\//);
  });

  it.each(uiFiles)('%s reaches src/server only as a Server Component', (file) => {
    const source = read(file);
    const isClientComponent = /^\s*['"]use client['"]/m.test(source);
    if (!isClientComponent) return; // Server Components may call server queries.
    expect(source, `${file} is a Client Component`).not.toMatch(/from\s+'[^']*server\//);
  });

  it('keeps the secret key reachable from exactly one module', () => {
    // The definition lives in config/env.ts; what matters is who imports it.
    const readers = serverFiles
      .filter((file) => file !== 'src/server/config/env.ts')
      .filter((file) => /import[\s\S]*?getSecretConfig[\s\S]*?from/.test(read(file)));
    expect(readers.map((file) => relative('src/server', file).replace(/\\/g, '/'))).toEqual([
      'supabase/admin-client.ts',
    ]);
  });
});

describe('no shared client state', () => {
  it.each(serverFiles)('%s builds no client at module load', (file) => {
    const source = read(file);
    // A client assigned at the top level would outlive the request and carry
    // one user's session into another's.
    expect(source).not.toMatch(/^(const|let|var)\s+\w+\s*=\s*(await\s+)?create\w*Client\(/m);
  });
});

describe('server-only guards', () => {
  it.each(serverFiles)('%s carries the server-only guard', (file) => {
    expect(read(file).includes("import 'server-only'")).toBe(true);
  });
});

describe('verified identity', () => {
  it('authorizes from getUser, never from getSession', () => {
    const viewer = read('src/server/auth/viewer.ts');
    expect(viewer).toMatch(/auth\.getUser\(\)/);
    expect(viewer).not.toMatch(/\.auth\.getSession\(/);
  });

  it('accepts no caller-supplied identity', () => {
    for (const file of serverFiles) {
      expect(read(file), file).not.toMatch(/\b(actorId|callerId|claimedUserId)\b/);
    }
  });
});
